// Generated by CoffeeScript 1.10.0
(function() {
  var Ohlc, _, assert, quandlData;

  Ohlc = require('../');

  assert = require('chai').assert;

  _ = require('lodash');

  quandlData = require('../quandlSample1570.json');

  describe("type test", function() {
    it("month data", function() {
      var data, data20160801, opts;
      opts = {
        type: 'month'
      };
      data = new Ohlc(quandlData.dataset.data, opts);
      data20160801 = _.find(data.objects, function(o) {
        return o.Date === '2016-08';
      });
      return assert.deepEqual(data20160801, {
        Date: '2016-08',
        Open: 10640,
        High: 11370,
        Low: 10040,
        Close: 11310,
        Volume: 195845183
      });
    });
    it("week data", function() {
      var data, data20160801, opts;
      opts = {
        type: 'week'
      };
      data = new Ohlc(quandlData.dataset.data, opts);
      data20160801 = _.find(data.objects, function(o) {
        return o.Date === '2016-08-01';
      });
      return assert.deepEqual(data20160801, {
        Date: '2016-08-01',
        Open: 10640,
        High: 11040,
        Low: 10040,
        Close: 10470,
        Volume: 61417462
      });
    });
    it("week data add Moveing Average", function() {
      var data, data20160801, opts;
      opts = {
        type: 'week',
        ma: [13, 26]
      };
      data = new Ohlc(quandlData.dataset.data, opts);
      data20160801 = _.find(data.objects, function(o) {
        return o.Date === '2016-08-01';
      });
      return assert.deepEqual(data20160801, {
        Date: '2016-08-01',
        Open: 10640,
        High: 11040,
        Low: 10040,
        Close: 10470,
        Volume: 61417462,
        ma13: 10508.46,
        ma26: 10751.54
      });
    });
    return it("month data add Moveing Average", function() {
      var data, data20160801, opts;
      opts = {
        type: 'm',
        ma: [12, 24]
      };
      data = new Ohlc(quandlData.dataset.data, opts);
      data20160801 = _.find(data.objects, function(o) {
        return o.Date === '2016-08';
      });
      return assert.deepEqual(data20160801, {
        Date: '2016-08',
        Open: 10640,
        High: 11370,
        Low: 10040,
        Close: 11310,
        Volume: 195845183,
        ma12: 12435.83,
        ma24: 13701.67
      });
    });
  });

}).call(this);
